/**
 * problem statement: https://atcoder.jp/contests/dp/tasks/dp_h
 * 
 */
function findTotalPaths(grid, m, n) {
    let dp = new Array(m+1).fill(0).map(() => new Array(n+1).fill(0));
    const mod = Math.pow(10, 7);
    console.log(mod);
    dp[m-1][n-1] = 1;
    for(let i=m-1; i>0;i--) {
        for(let j=n-1;j>0;j--) {
            if(grid[i-1][j]!=='#') {
                dp[i-1][j] = (dp[i][j]+ dp[i-1][j+1])%mod;
            }
            if(grid[i][j-1] !== '#') {
                dp[i][j-1] = (dp[i][j] + dp[i+1][j-1])%mod;
            }
        }
    }
    dp[0][0] = (dp[0][1] + dp[1][0])%mod; 
    console.log(dp[0][0]);
}
const grid1 = `..#..
.....
#...#
.....
..#..`.split('\n').map((a) => a.split(''));
const grid = [
    '...#'.split(''),
    '.#..'.split(''),
    '....'.split(''),
];
const grid2 = `....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................
....................`.split('\n').map(a => a.split(''));
console.log(grid2.length, grid2[0].length);
const grid3= `..
#.
..
.#
..`.split('\n').map((a) => a.split(''));
findTotalPaths(grid3, grid3.length, grid3[0].length);